// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ggezchain/denomfactory/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetDenomIndexRequest struct {
}

func (m *QueryGetDenomIndexRequest) Reset()         { *m = QueryGetDenomIndexRequest{} }
func (m *QueryGetDenomIndexRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDenomIndexRequest) ProtoMessage()    {}
func (*QueryGetDenomIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{2}
}
func (m *QueryGetDenomIndexRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDenomIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDenomIndexRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDenomIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDenomIndexRequest.Merge(m, src)
}
func (m *QueryGetDenomIndexRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDenomIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDenomIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDenomIndexRequest proto.InternalMessageInfo

type QueryGetDenomIndexResponse struct {
	DenomIndex DenomIndex `protobuf:"bytes,1,opt,name=DenomIndex,proto3" json:"DenomIndex"`
}

func (m *QueryGetDenomIndexResponse) Reset()         { *m = QueryGetDenomIndexResponse{} }
func (m *QueryGetDenomIndexResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDenomIndexResponse) ProtoMessage()    {}
func (*QueryGetDenomIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{3}
}
func (m *QueryGetDenomIndexResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDenomIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDenomIndexResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDenomIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDenomIndexResponse.Merge(m, src)
}
func (m *QueryGetDenomIndexResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDenomIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDenomIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDenomIndexResponse proto.InternalMessageInfo

func (m *QueryGetDenomIndexResponse) GetDenomIndex() DenomIndex {
	if m != nil {
		return m.DenomIndex
	}
	return DenomIndex{}
}

type QueryGetNewCoinRequest struct {
	DenomIndex string `protobuf:"bytes,1,opt,name=denomIndex,proto3" json:"denomIndex,omitempty"`
}

func (m *QueryGetNewCoinRequest) Reset()         { *m = QueryGetNewCoinRequest{} }
func (m *QueryGetNewCoinRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNewCoinRequest) ProtoMessage()    {}
func (*QueryGetNewCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{4}
}
func (m *QueryGetNewCoinRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNewCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNewCoinRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNewCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNewCoinRequest.Merge(m, src)
}
func (m *QueryGetNewCoinRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNewCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNewCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNewCoinRequest proto.InternalMessageInfo

func (m *QueryGetNewCoinRequest) GetDenomIndex() string {
	if m != nil {
		return m.DenomIndex
	}
	return ""
}

type QueryGetNewCoinResponse struct {
	NewCoin NewCoin `protobuf:"bytes,1,opt,name=newCoin,proto3" json:"newCoin"`
}

func (m *QueryGetNewCoinResponse) Reset()         { *m = QueryGetNewCoinResponse{} }
func (m *QueryGetNewCoinResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNewCoinResponse) ProtoMessage()    {}
func (*QueryGetNewCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{5}
}
func (m *QueryGetNewCoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNewCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNewCoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNewCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNewCoinResponse.Merge(m, src)
}
func (m *QueryGetNewCoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNewCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNewCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNewCoinResponse proto.InternalMessageInfo

func (m *QueryGetNewCoinResponse) GetNewCoin() NewCoin {
	if m != nil {
		return m.NewCoin
	}
	return NewCoin{}
}

type QueryAllNewCoinRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNewCoinRequest) Reset()         { *m = QueryAllNewCoinRequest{} }
func (m *QueryAllNewCoinRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNewCoinRequest) ProtoMessage()    {}
func (*QueryAllNewCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{6}
}
func (m *QueryAllNewCoinRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNewCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNewCoinRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNewCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNewCoinRequest.Merge(m, src)
}
func (m *QueryAllNewCoinRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNewCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNewCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNewCoinRequest proto.InternalMessageInfo

func (m *QueryAllNewCoinRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllNewCoinResponse struct {
	NewCoin    []NewCoin           `protobuf:"bytes,1,rep,name=newCoin,proto3" json:"newCoin"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNewCoinResponse) Reset()         { *m = QueryAllNewCoinResponse{} }
func (m *QueryAllNewCoinResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNewCoinResponse) ProtoMessage()    {}
func (*QueryAllNewCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b9d80876666c4d, []int{7}
}
func (m *QueryAllNewCoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNewCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNewCoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNewCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNewCoinResponse.Merge(m, src)
}
func (m *QueryAllNewCoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNewCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNewCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNewCoinResponse proto.InternalMessageInfo

func (m *QueryAllNewCoinResponse) GetNewCoin() []NewCoin {
	if m != nil {
		return m.NewCoin
	}
	return nil
}

func (m *QueryAllNewCoinResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ggezchain.denomfactory.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ggezchain.denomfactory.QueryParamsResponse")
	proto.RegisterType((*QueryGetDenomIndexRequest)(nil), "ggezchain.denomfactory.QueryGetDenomIndexRequest")
	proto.RegisterType((*QueryGetDenomIndexResponse)(nil), "ggezchain.denomfactory.QueryGetDenomIndexResponse")
	proto.RegisterType((*QueryGetNewCoinRequest)(nil), "ggezchain.denomfactory.QueryGetNewCoinRequest")
	proto.RegisterType((*QueryGetNewCoinResponse)(nil), "ggezchain.denomfactory.QueryGetNewCoinResponse")
	proto.RegisterType((*QueryAllNewCoinRequest)(nil), "ggezchain.denomfactory.QueryAllNewCoinRequest")
	proto.RegisterType((*QueryAllNewCoinResponse)(nil), "ggezchain.denomfactory.QueryAllNewCoinResponse")
}

func init() {
	proto.RegisterFile("ggezchain/denomfactory/query.proto", fileDescriptor_10b9d80876666c4d)
}

var fileDescriptor_10b9d80876666c4d = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6f, 0x12, 0x4f,
	0x18, 0xc6, 0xd9, 0xfe, 0xff, 0xa5, 0xf1, 0xf5, 0x36, 0x36, 0x55, 0x57, 0xb3, 0x35, 0x63, 0xd4,
	0x5a, 0xe2, 0x8c, 0x50, 0x63, 0x1a, 0x63, 0xa2, 0xad, 0xc6, 0xea, 0xa5, 0xa9, 0x78, 0xeb, 0xa5,
	0x0e, 0x30, 0x5d, 0x36, 0x81, 0x99, 0x2d, 0xbb, 0xd8, 0xa2, 0xf1, 0xe2, 0x27, 0x30, 0xd1, 0x0f,
	0x60, 0xf4, 0xa8, 0x1f, 0xa4, 0xc7, 0x26, 0x5e, 0x3c, 0x19, 0x03, 0x7e, 0x10, 0xc3, 0xcc, 0x8b,
	0x2c, 0xb2, 0x5b, 0xe0, 0x06, 0xef, 0x3c, 0xcf, 0xfb, 0xfc, 0x02, 0xcf, 0x0c, 0x50, 0xdf, 0x97,
	0xaf, 0xab, 0x75, 0x11, 0x28, 0x5e, 0x93, 0x4a, 0x37, 0xf7, 0x45, 0x35, 0xd6, 0xad, 0x0e, 0x3f,
	0x68, 0xcb, 0x56, 0x87, 0x85, 0x2d, 0x1d, 0x6b, 0xb2, 0xf4, 0x57, 0xc3, 0x92, 0x1a, 0x77, 0xd1,
	0xd7, 0xbe, 0x36, 0x12, 0xde, 0xff, 0x64, 0xd5, 0xee, 0x65, 0x5f, 0x6b, 0xbf, 0x21, 0xb9, 0x08,
	0x03, 0x2e, 0x94, 0xd2, 0xb1, 0x88, 0x03, 0xad, 0x22, 0x3c, 0x5d, 0xad, 0xea, 0xa8, 0xa9, 0x23,
	0x5e, 0x11, 0x91, 0xb4, 0x21, 0xfc, 0x55, 0xb1, 0x22, 0x63, 0x51, 0xe4, 0xa1, 0xf0, 0x03, 0x65,
	0xc4, 0xa8, 0xbd, 0x9a, 0xc1, 0x16, 0x8a, 0x96, 0x68, 0x0e, 0x16, 0xae, 0x64, 0x88, 0xcc, 0x97,
	0xbd, 0x40, 0xd5, 0xe4, 0x11, 0x2a, 0xaf, 0x65, 0x28, 0x95, 0x3c, 0xdc, 0xab, 0xea, 0x00, 0x53,
	0xe9, 0x22, 0x90, 0xe7, 0x7d, 0xae, 0x1d, 0x93, 0x52, 0x96, 0x07, 0x6d, 0x19, 0xc5, 0xf4, 0x05,
	0x9c, 0x1b, 0x99, 0x46, 0xa1, 0x56, 0x91, 0x24, 0xf7, 0x21, 0x6f, 0x69, 0x2e, 0x38, 0x57, 0x9c,
	0x95, 0xb3, 0x25, 0x8f, 0xa5, 0xff, 0x56, 0xcc, 0xfa, 0x36, 0xff, 0x3f, 0xfe, 0xb9, 0x9c, 0x2b,
	0xa3, 0x87, 0x5e, 0x82, 0x8b, 0x66, 0xe9, 0x96, 0x8c, 0x1f, 0xf7, 0xc5, 0xcf, 0xfa, 0xb4, 0x83,
	0xc4, 0x7d, 0x70, 0xd3, 0x0e, 0x31, 0xf8, 0x29, 0xc0, 0x70, 0x8a, 0xe1, 0x34, 0x2b, 0x7c, 0xa8,
	0x44, 0x80, 0x84, 0x97, 0xae, 0xc3, 0xd2, 0x20, 0x67, 0x5b, 0x1e, 0x3e, 0xd2, 0x81, 0x42, 0x02,
	0xe2, 0x01, 0xd4, 0x46, 0x33, 0xce, 0x94, 0x13, 0x13, 0xba, 0x0b, 0xe7, 0xc7, 0x9c, 0x88, 0xf7,
	0x00, 0x16, 0x94, 0x1d, 0x21, 0xdb, 0x72, 0x16, 0x1b, 0x3a, 0x11, 0x6c, 0xe0, 0xa2, 0x2f, 0x91,
	0x6a, 0xa3, 0xd1, 0xf8, 0x87, 0xea, 0x09, 0xc0, 0xb0, 0x29, 0xb8, 0xfd, 0x3a, 0xb3, 0xb5, 0x62,
	0xfd, 0x5a, 0x31, 0xdb, 0x5d, 0xac, 0x15, 0xdb, 0x11, 0xbe, 0x44, 0x6f, 0x39, 0xe1, 0xa4, 0x5f,
	0x1c, 0xc4, 0x4f, 0x46, 0xa4, 0xe1, 0xff, 0x37, 0x3b, 0x3e, 0xd9, 0x1a, 0x81, 0x9c, 0x33, 0x90,
	0x37, 0x26, 0x42, 0xda, 0xf4, 0x24, 0x65, 0xe9, 0xd3, 0x3c, 0xcc, 0x1b, 0x4a, 0xf2, 0xd1, 0x81,
	0xbc, 0x6d, 0x11, 0x59, 0xcd, 0xa2, 0x19, 0x2f, 0xae, 0x5b, 0x98, 0x4a, 0x6b, 0x93, 0x69, 0xf1,
	0xdd, 0xf7, 0xdf, 0x1f, 0xe6, 0x0a, 0xe4, 0x26, 0x6f, 0xea, 0x76, 0x24, 0x82, 0x4a, 0x4b, 0xd4,
	0xf9, 0xa9, 0xb7, 0x90, 0x7c, 0x75, 0x92, 0x4d, 0x24, 0xc5, 0x53, 0xe3, 0xd2, 0x8a, 0xee, 0x96,
	0x66, 0xb1, 0x20, 0xe8, 0x5d, 0x03, 0x7a, 0x9b, 0xb0, 0x29, 0x40, 0x13, 0x2f, 0x01, 0xf9, 0xe6,
	0xc0, 0x02, 0xfe, 0x65, 0x84, 0x4d, 0xca, 0x1d, 0x2d, 0x9e, 0xcb, 0xa7, 0xd6, 0x23, 0xe4, 0x43,
	0x03, 0x79, 0x8f, 0xac, 0x4f, 0x01, 0x39, 0x78, 0x84, 0xf8, 0x9b, 0xe1, 0x05, 0x7b, 0x4b, 0x3e,
	0x3b, 0x00, 0xb8, 0x75, 0xa3, 0xd1, 0x98, 0x40, 0x3c, 0x76, 0x55, 0x26, 0x10, 0x8f, 0xf7, 0x9e,
	0xae, 0x19, 0xe2, 0x5b, 0xa4, 0x30, 0x03, 0xf1, 0xe6, 0xf6, 0x71, 0xd7, 0x73, 0x4e, 0xba, 0x9e,
	0xf3, 0xab, 0xeb, 0x39, 0xef, 0x7b, 0x5e, 0xee, 0xa4, 0xe7, 0xe5, 0x7e, 0xf4, 0xbc, 0xdc, 0xee,
	0x1d, 0x3f, 0x88, 0xeb, 0xed, 0x0a, 0xab, 0xea, 0x66, 0xfa, 0xc2, 0xa3, 0xd1, 0x95, 0x71, 0x27,
	0x94, 0x51, 0x25, 0x6f, 0xde, 0xe1, 0xb5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x28, 0xe5,
	0x91, 0x9b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a DenomIndex by index.
	DenomIndex(ctx context.Context, in *QueryGetDenomIndexRequest, opts ...grpc.CallOption) (*QueryGetDenomIndexResponse, error)
	// Queries a list of NewCoin items.
	NewCoin(ctx context.Context, in *QueryGetNewCoinRequest, opts ...grpc.CallOption) (*QueryGetNewCoinResponse, error)
	NewCoinAll(ctx context.Context, in *QueryAllNewCoinRequest, opts ...grpc.CallOption) (*QueryAllNewCoinResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.denomfactory.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomIndex(ctx context.Context, in *QueryGetDenomIndexRequest, opts ...grpc.CallOption) (*QueryGetDenomIndexResponse, error) {
	out := new(QueryGetDenomIndexResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.denomfactory.Query/DenomIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewCoin(ctx context.Context, in *QueryGetNewCoinRequest, opts ...grpc.CallOption) (*QueryGetNewCoinResponse, error) {
	out := new(QueryGetNewCoinResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.denomfactory.Query/NewCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewCoinAll(ctx context.Context, in *QueryAllNewCoinRequest, opts ...grpc.CallOption) (*QueryAllNewCoinResponse, error) {
	out := new(QueryAllNewCoinResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.denomfactory.Query/NewCoinAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a DenomIndex by index.
	DenomIndex(context.Context, *QueryGetDenomIndexRequest) (*QueryGetDenomIndexResponse, error)
	// Queries a list of NewCoin items.
	NewCoin(context.Context, *QueryGetNewCoinRequest) (*QueryGetNewCoinResponse, error)
	NewCoinAll(context.Context, *QueryAllNewCoinRequest) (*QueryAllNewCoinResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DenomIndex(ctx context.Context, req *QueryGetDenomIndexRequest) (*QueryGetDenomIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomIndex not implemented")
}
func (*UnimplementedQueryServer) NewCoin(ctx context.Context, req *QueryGetNewCoinRequest) (*QueryGetNewCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewCoin not implemented")
}
func (*UnimplementedQueryServer) NewCoinAll(ctx context.Context, req *QueryAllNewCoinRequest) (*QueryAllNewCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewCoinAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.denomfactory.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDenomIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.denomfactory.Query/DenomIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomIndex(ctx, req.(*QueryGetDenomIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNewCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.denomfactory.Query/NewCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewCoin(ctx, req.(*QueryGetNewCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewCoinAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNewCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewCoinAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.denomfactory.Query/NewCoinAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewCoinAll(ctx, req.(*QueryAllNewCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ggezchain.denomfactory.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DenomIndex",
			Handler:    _Query_DenomIndex_Handler,
		},
		{
			MethodName: "NewCoin",
			Handler:    _Query_NewCoin_Handler,
		},
		{
			MethodName: "NewCoinAll",
			Handler:    _Query_NewCoinAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ggezchain/denomfactory/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDenomIndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDenomIndexRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDenomIndexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetDenomIndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDenomIndexResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDenomIndexResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DenomIndex.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetNewCoinRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNewCoinRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNewCoinRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomIndex) > 0 {
		i -= len(m.DenomIndex)
		copy(dAtA[i:], m.DenomIndex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DenomIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNewCoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNewCoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNewCoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NewCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllNewCoinRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNewCoinRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNewCoinRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNewCoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNewCoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNewCoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NewCoin) > 0 {
		for iNdEx := len(m.NewCoin) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NewCoin[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDenomIndexRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetDenomIndexResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DenomIndex.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetNewCoinRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DenomIndex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNewCoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NewCoin.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllNewCoinRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNewCoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NewCoin) > 0 {
		for _, e := range m.NewCoin {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDenomIndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDenomIndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDenomIndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDenomIndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDenomIndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDenomIndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DenomIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNewCoinRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNewCoinRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNewCoinRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNewCoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNewCoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNewCoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNewCoinRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNewCoinRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNewCoinRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNewCoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNewCoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNewCoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewCoin = append(m.NewCoin, NewCoin{})
			if err := m.NewCoin[len(m.NewCoin)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
